apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-swagger-svc
  namespace: ${CICD_GIT_REPO_NAME}
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-swagger
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-swagger
  ports:
    - name: swaggereditor
      protocol: TCP
      port: 8080
